export { default as Login } from "./Login";
export { default as Journals } from "./Journals";
export { default as CreateJournal } from "./CreateJournal";
export { default as Home } from "./Home";
export { default as JournalId } from "./JournalId";
export { default as EditJournal } from "./EditJournal";
export { default as ArticlePage } from "./articles/ArticlePage";
export { default as ConferencePage } from "./conference/ConferencePage";
export { default as ConferenceCreate } from "./conference/ConferenceCreate";
